export const services = [
  'Abuse\nTrauma',
  'Addictive\nBehaviors',
  'Anger\nManagement',
  'Anxiety\nPanic',
  'Boundaries',
  'Burnout',
  'Codependency\nIssues',
  // 'Cultural\nDiversity\nIssues',
  'Depression\nDespair',
  'Emotional\nRegulation',
  'Family\nDysfunction',
  'Faith\nStruggles',
  'Fears\nPhobias',
  'Grief\nLoss',
  'Guilt\nShame',
  'Infidelity',
  'Marital\nStruggles',
  // 'Minority\nIssues',
  'Obsessive\nCompulsive\nBehaviors',
  'Parenting',
  'Pastoral\nand\nChurch\nDynamics',
  'Premarital\nRelationships',
  'Self-esteem',
  'Sexuality',
  'Spiritual\nGrowth\nJourneys',
  'Stress\nManagement',
  'Suicidal\nIdeation',
];
